#pragma config(Motor,  port3,           FrontLeft,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           FrontRight,    tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port5,           BackRight,     tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port6,           BackLeft,      tmotorVex393_MC29, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*********************************
*Hoya Robotics
*Ontario Skills 2021
*Builder Robot
*Will Tempest
************************************/
task main()
{
while(true){
	//all code that is part of main loop goes here
	//Drive forward/back
	motor[FrontLeft] = vexRT[Ch3];
	motor[BackLeft] = vexRT[Ch3];
	motor[FrontRight] = vexRT[Ch3];
	motor[BackRight] = vexRT[Ch3];
	
	//Turn Left/Right
	motor[FrontLeft] = vexRT[Ch4];
	motor[BackLeft] = vexRT[Ch4];
	motor[FrontRight] = -1*vexRT[Ch4];
	motor[BackRight] = -1*vexRT[Ch4];	
}//end while loop
}//end task
